### PR TITLE
updated to latest erc875 spec

### PR DESCRIPTION
**Pull request by JamesANZ**
for #3

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by hboon** [comment]
@James-Sangalli can you format the args to `web3.eth.contract(` in a similar way to the original so the diff is more meaningful?

**Comment by JamesANZ** [comment]
@hboon would prefer it compact, it is pretty simple and takes up a lot of space. Cheers for looking!

**Pull request merged**
